### ISSUE TITLE
Implement groups

### ISSUE THREAD

**Issue by w4** [w4/chartered#18]
All crates should be scoped to a group - group permissions will apply to crate permissions by default, however the crate permissions can be overridden. Group admins decide who gets to push new crates with the new permission `NEW_CRATE`.

Any attempts to push to an unscoped crate (ie. `rand`, instead of `my-group/rand`) will be disallowed.

This means per-group registries will have to be defined in `~/.cargo/config.toml`:

```toml
[registries]
registry--cool   = { index = "ssh://chart.rs/cool" }
registry--uncool = { index = "ssh://chart.rs/uncool" }
```

This change should also allow for "global" permissions
